FROM node:26.1-alpine3.23

RUN npm install -g pnpm@11.1.2

WORKDIR /frontend

COPY ./frontend/package.json ./
COPY ./frontend/pnpm-lock.yaml ./

RUN pnpm ci

COPY ./frontend/public ./public
COPY ./frontend/src ./src

COPY ./frontend/eslint.config.js ./
COPY ./frontend/index.html ./
COPY ./frontend/tsconfig.json ./
COPY ./frontend/tsconfig.app.json ./
COPY ./frontend/tsconfig.node.json ./
COPY ./frontend/vite.config.ts ./

EXPOSE 5173

ENTRYPOINT ["pnpm", "run", "dev"]
