// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type OidcCode struct {
	Sub           string
	CodeHash      string
	Scope         string
	RedirectURI   string
	ClientID      string
	ExpiresAt     int64
	Nonce         string
	CodeChallenge string
}

type OidcToken struct {
	Sub                   string
	AccessTokenHash       string
	RefreshTokenHash      string
	CodeHash              string
	Scope                 string
	ClientID              string
	TokenExpiresAt        int64
	RefreshTokenExpiresAt int64
	Nonce                 string
}

type OidcUserinfo struct {
	Sub               string
	Name              string
	PreferredUsername string
	Email             string
	Groups            string
	UpdatedAt         int64
	GivenName         string
	FamilyName        string
	MiddleName        string
	Nickname          string
	Profile           string
	Picture           string
	Website           string
	Gender            string
	Birthdate         string
	Zoneinfo          string
	Locale            string
	PhoneNumber       string
	Address           string
}

type Session struct {
	UUID        string
	Username    string
	Email       string
	Name        string
	Provider    string
	TotpPending bool
	OAuthGroups string
	Expiry      int64
	CreatedAt   int64
	OAuthName   string
	OAuthSub    string
}
