name: Bug Report
description: Create a report to help us improve this project
title: "[BUG]"
labels: bug
assignees:
- steveiliop56

body:
- type: markdown
  attributes:
    value: |
      Thanks for reporting a bug! Please provide detailed information below.

- type: textarea
  id: description
  attributes:
    label: Describe the Bug
    description: "A clear and concise description of what the bug is."
  validations:
    required: true

- type: textarea
  id: reproduce
  attributes:
    label: How to Reproduce
    description: Steps to reproduce the behavior.
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false

- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: "A clear and concise description of what you expected to happen."
  validations:
    required: true

- type: textarea
  id: context
  attributes:
    label: "Additional Context"
    description: "If applicable add screenshots to help explain your problem."
  validations:
    required: false

- type: textarea
  id: logs
  attributes:
    label: "Logs"
    description: "Please include the Tinyauth logs, make sure to not include sensitive info."
  validations:
    required: false

- type: input
  id: os
  attributes:
    label: Operating System
    placeholder: "e.g. iOS, android, windows, linux, etc"

- type: input
  id: browser
  attributes:
    label: Browser
    placeholder: "e.g. chrome, firefox, safari, edge, etc"

- type: input
  id: tinyauth
  attributes:
    label: Tinyauth Version
    placeholder: "e.g. v5.0.0"

- type: input
  id: docker
  attributes:
    label: Docker Version (if applicable)
    placeholder: "e.g. 27.3.1"

- type: checkboxes
  id: not-llm
  attributes:
    label: Human Written Confirmation
    options:
      - label: I confirm this issue was written by me and not generated by an LLM or AI assistant.
        required: true
