CREATE TABLE IF NOT EXISTS "oidc_consent" (
    "uuid" TEXT NOT NULL UNIQUE PRIMARY KEY,
    "client_id" TEXT NOT NULL,
    "scopes" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
