name: Tinyauth CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.26.0"

      - name: Go dependencies
        run: go mod download

      - name: Install frontend dependencies
        run: |
          cd frontend
          bun install --frozen-lockfile

      - name: Set version
        run: |
          echo testing > internal/assets/version

      - name: Lint frontend
        run: |
          cd frontend
          bun run lint

      - name: Build frontend
        run: |
          cd frontend
          bun run build

      - name: Copy frontend
        run: |
          cp -r frontend/dist internal/assets/dist

      - name: Run tests
        run: go test -coverprofile=coverage.txt -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
