name: Tinyauth CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          package_json_file: ./frontend/package.json

      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: "^1.26.0"

      - name: Go dependencies
        run: go mod download

      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v5
        with:
          sqlc-version: "1.31.1"

      - name: Check codegen is up to date
        run: |
          sqlc generate
          go generate ./internal/repository/...
          git diff --exit-code -- internal/repository/
          git status --porcelain -- internal/repository/ | grep -q . && echo "untracked files in internal/repository/" && exit 1 || true

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: pnpm ci

      - name: Set version
        run: echo testing > internal/assets/version

      - name: Lint frontend
        working-directory: ./frontend
        run: pnpm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: pnpm run build

      - name: Copy frontend
        run: cp -r frontend/dist internal/assets/dist

      - name: Run tests
        run: go test -coverprofile=coverage.txt -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
