name: Tinyauth CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: ./frontend/package.json

      - name: Setup go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "^1.26.4"

      - name: Go dependencies
        run: go mod download

      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v5
        with:
          sqlc-version: "1.31.1"

      - name: Check codegen is up to date
        run: |
          sqlc generate
          go generate ./...
          git diff --exit-code
          git status --porcelain | grep -q . && echo "untracked files code gen files" && exit 1 || true

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: pnpm ci

      - name: Set version
        run: echo testing > internal/assets/version

      - name: Lint frontend
        working-directory: ./frontend
        run: pnpm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: pnpm run build

      - name: Copy frontend
        run: cp -r frontend/dist internal/assets/dist

      - name: Run tests
        run: go test -coverprofile=coverage.txt -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
